### ISSUE TITLE
App Checklist

### ISSUE THREAD

**Issue by faseehahmed1** [faseehahmed1/super-market-app#1]
## Static Site
- [ ] NavBar
- [ ] Home Page
- [ ] About Us
- [ ] Products Page
- [ ] Cart

## Code
- [ ] Setup FireBase API
- [ ] Pass in real data
- [ ] use Custom hook
